### ISSUE TITLE
NPEs for everyone in configuration

### ISSUE THREAD

**Issue by danyill** [danyill/fscrawler#5]
``` json
{
  "name" : "test",
  "fs" : {
    "json_support" : true,
    "filename_as_id" : true
  }
}
```

``` bash
14:55:28,421 WARN  [f.p.e.c.f.FsCrawlerImpl] `url` is not set. Please define it. Falling back to default: [/tmp/es].
14:55:28,429 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
14:55:30,825 INFO  [f.p.e.c.f.FsCrawlerImpl] creating fs crawler thread [test07] for [/tmp/es] every [null]
Exception in thread "Thread-2" java.lang.NullPointerException
    at fr.pilato.elasticsearch.crawler.fs.FsCrawlerImpl$FSParser.run(FsCrawlerImpl.java:235)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by danyill** [comment]
Need to fix this generically, also a problem with: 

``` json
{
  "name" : "test",
  "fs" : {
    "add_filesize" : false
  }
}
```
